### ISSUE TITLE
Consider transferring to contrib organization

### ISSUE THREAD

**Issue by thomashoneyman** [purescript-contrib/purescript-colors#47]
Hi @sharkdp!

I'm a member of the PureScript core team and the PureScript Contributors organization (purescript-contrib). We're in the midst of a new PureScript release and I noticed that one or more of our libraries depends on this one.

In general we don't allow libraries from the contrib organization to depend on libraries outside it (or core). This ensures that the core team can make all necessary updates when making a new compiler release.

I noticed while reading through other issues that you aren't actively maintaining this library anymore. Would you be open to transferring it to the purescript-contrib organization, where we will ensure it's updated for each compiler release? You would certainly be able to stay on as the primary maintainer if you wanted to -- but you wouldn't have to if you'd rather not.

Thanks for your time! Let me know what you think!

**Comment by sharkdp** [comment]
> Would you be open to transferring it to the purescript-contrib organization, where we will ensure it's updated for each compiler release?

Absolutely. That would be fantastic. Glad to hear that the library is still of use.

> You would certainly be able to stay on as the primary maintainer if you wanted to -- but you wouldn't have to if you'd rather not.

I would prefer if someone else could take over the maintainership.

**Comment by thomashoneyman** [comment]
Great to hear!

> Let me know what steps I need to take to transfer the repo or the access rights.

You can either add me as an owner to this repository and I can transfer it for you, or I can add you as a member of the `purescript-contrib` organization, and then you can transfer it. Completely up to you!

**Comment by sharkdp** [comment]
invited you as a maintainer

**Comment by thomashoneyman** [comment]
For all the nitty-gritty details: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by sharkdp** [comment]
I don't see any option to make you admin or owner. Maybe that's not possible for user-owned repos (which are not part of an org). You'd either need to add me to purescript-contrib, or I might need to transfer the repo to your user first(?).

**Comment by thomashoneyman** [comment]
I've invited you to the organization so that you can transfer. Afterwards, if you'd like, you can leave the organization (but you're welcome to stay!).

**Comment by sharkdp** [comment]
transferred. Thank you!

**Comment by thomashoneyman** [comment]
Thanks!
